# Generated by Django 2.0.6 on 2020-03-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('status', models.NullBooleanField()),
                ('create_time', models.DateField()),
                ('content', models.CharField(max_length=5000)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Article_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artical_images')),
                ('create_time', models.DateField()),
            ],
            options={
                'db_table': 'article_image',
            },
        ),
    ]
