# Generated by Django 2.0.6 on 2020-03-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('status', models.NullBooleanField()),
                ('create_time', models.DateTimeField()),
                ('pic', models.ImageField(upload_to='pic')),
            ],
            options={
                'db_table': 'banner',
            },
        ),
    ]
